# Generated by Django 5.2.6 on 2025-10-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tipoalerta_alter_salud_usuario_alter_condicion_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_activa',
            field=models.BooleanField(default=False),
        ),
    ]
