# Generated by Django 5.2.6 on 2025-11-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaCaminata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_recorridos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pasos', models.IntegerField()),
                ('tiempo_actividad', models.DurationField()),
                ('velocidad_promedio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calorias_quemadas', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'metrica_caminata',
            },
        ),
        migrations.CreateModel(
            name='MetricaCorazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ritmo_cardiaco', models.IntegerField()),
                ('presion', models.CharField(max_length=50)),
                ('oxigenacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'metrica_corazon',
            },
        ),
        migrations.CreateModel(
            name='SesionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('ubicacion_inicial', models.FloatField(blank=True, null=True)),
                ('ubicacion_final', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sesion_actividad',
            },
        ),
    ]
