# Generated by Django 5.2.6 on 2025-11-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0001_initial'),
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionactividad',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.cita'),
        ),
        migrations.AddField(
            model_name='sesionactividad',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.ruta'),
        ),
    ]
