# Generated by Django 5.2.6 on 2025-10-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionactividad',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trail.ruta'),
        ),
    ]
