# Generated by Django 5.2.6 on 2025-10-20 06:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesionactividad',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.cita'),
        ),
        migrations.AlterField(
            model_name='sesionactividad',
            name='fecha_hora_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesionactividad',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trail.ruta'),
        ),
        migrations.AlterField(
            model_name='sesionactividad',
            name='ubicacion_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sesionactividad',
            name='ubicacion_inicial',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='metricacaminata',
            table='metrica_caminata',
        ),
        migrations.AlterModelTable(
            name='metricacorazon',
            table='metrica_corazon',
        ),
        migrations.AlterModelTable(
            name='sesionactividad',
            table='sesion_actividad',
        ),
    ]
