# Generated by Django 5.2.6 on 2025-12-08 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaMonitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('ritmo_alto', 'Ritmo cardíaco alto'), ('ritmo_bajo', 'Ritmo cardíaco bajo'), ('oxigenacion_baja', 'Oxigenación baja'), ('inactividad', 'Inactividad prolongada'), ('info', 'Información')], max_length=20)),
                ('mensaje', models.TextField()),
                ('ritmo_cardiaco', models.IntegerField(blank=True, null=True)),
                ('oxigenacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('leida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerta de Monitoreo',
                'verbose_name_plural': 'Alertas de Monitoreo',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
