# Generated by Django 5.2.6 on 2025-09-28 22:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('ID_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='archivos/')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAlerta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=128)),
                ('importancia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('nivel', models.IntegerField()),
                ('descripcion', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.contactoemergencia')),
                ('tipo_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='MetricaCaminata',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('km_recorridos', models.CharField(max_length=50)),
                ('pasos', models.IntegerField()),
                ('tiempo_actividad', models.CharField(max_length=50)),
                ('velocidad_promedio', models.CharField(max_length=50)),
                ('calorias_quemadas', models.CharField(max_length=50)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricaCorazon',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ritmo_cardiaco', models.FloatField()),
                ('presion', models.FloatField()),
                ('oxigenacion', models.FloatField()),
                ('fecha_hora', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_experiencia', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mapa')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_visita', models.DateTimeField()),
                ('hora_retorno', models.DateTimeField()),
                ('clima', models.CharField(max_length=200)),
                ('recomendaciones', models.TextField()),
                ('compania', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='SaludUsuario',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.FloatField()),
                ('condicion', models.IntegerField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessionActividad',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(auto_now_add=True)),
                ('ubicacion_inicial', models.FloatField()),
                ('ubicacion_final', models.FloatField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioAlerta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoalerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
