# Generated by Django 5.2.6 on 2025-09-30 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionactividad',
            name='cita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cita'),
            preserve_default=False,
        ),
    ]
