# Generated by Django 5.2.6 on 2025-09-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessionactividad_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactividad',
            name='fecha_hora_fin',
            field=models.DateTimeField(),
        ),
    ]
