# Generated by Django 5.2.6 on 2025-09-30 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sessionactividad_fecha_hora_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactividad',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cita'),
        ),
    ]
