# Generated by Django 5.2.6 on 2025-09-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sessionactividad_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactividad',
            name='fecha_hora_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
