# Generated by Django 5.2.6 on 2025-10-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sessionactividad_fecha_hora_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='session_activa',
            field=models.BooleanField(default=False),
        ),
    ]
