# Generated by Django 5.2.6 on 2025-10-02 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_session_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionactividad',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ruta'),
        ),
    ]
