# Generated by Django 5.2.6 on 2025-10-02 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_sessionactividad_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricacaminata',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessionactividad'),
        ),
        migrations.AlterField(
            model_name='metricacorazon',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessionactividad'),
        ),
    ]
