# Generated by Django 5.2.6 on 2025-11-27 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariogrupo',
            name='fecha_invitacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariogrupo',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
    ]
