# Generated by Django 5.2.6 on 2025-10-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioretorno',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='horarioretorno',
            name='ruta',
        ),
        migrations.RemoveField(
            model_name='horarioretorno',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='grupo',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariogrupo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='grupo',
            table='grupo',
        ),
        migrations.AlterModelTable(
            name='usuariogrupo',
            table='usuario_grupo',
        ),
        migrations.DeleteModel(
            name='ContactoEmergencia',
        ),
        migrations.DeleteModel(
            name='HorarioRetorno',
        ),
    ]
