# Generated by Django 5.2.6 on 2025-10-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUsuarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tiempo_duracion', models.DurationField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=50)),
                ('satisfaccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_mapa', models.TextField()),
                ('disponible_offline', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ruta', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nivel_experiencia', models.CharField(max_length=50)),
                ('mapa_url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
