# Generated by Django 5.2.6 on 2025-11-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialUsuarioRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tiempo_duracion', models.DurationField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=50)),
                ('satisfaccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'historial_usuario_ruta',
            },
        ),
        migrations.CreateModel(
            name='InvitacionCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_invitacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invitacion_cita',
            },
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='../archivos/')),
            ],
            options={
                'db_table': 'mapa',
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('nivel_experiencia', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
            options={
                'db_table': 'ruta',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('clima', models.CharField(max_length=200)),
                ('recomendaciones', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.grupo')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
    ]
