# Generated by Django 5.2.6 on 2025-10-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioretorno',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='horarioretorno',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='mapa',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='ruta',
            name='ID',
        ),
        migrations.DeleteModel(
            name='ContactoEmergencia',
        ),
        migrations.DeleteModel(
            name='HorarioRetorno',
        ),
        migrations.AddField(
            model_name='mapa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='ruta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
