# Generated by Django 5.2.6 on 2025-11-03 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialusuarioruta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitacioncita',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.cita'),
        ),
        migrations.AddField(
            model_name='invitacioncita',
            name='invitado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='invitados',
            field=models.ManyToManyField(blank=True, related_name='citas_invitado', through='trail.InvitacionCita', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruta',
            name='mapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.mapa'),
        ),
        migrations.AddField(
            model_name='historialusuarioruta',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.ruta'),
        ),
        migrations.AddField(
            model_name='cita',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.ruta'),
        ),
        migrations.AlterUniqueTogether(
            name='invitacioncita',
            unique_together={('cita', 'invitado')},
        ),
    ]
