# Generated by Django 5.2.6 on 2025-10-20 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_horarioretorno_contacto_and_more'),
        ('trail', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historialusuarioruta',
            table='historial_usuario_ruta',
        ),
        migrations.AlterModelTable(
            name='mapa',
            table='mapa',
        ),
        migrations.AlterModelTable(
            name='ruta',
            table='ruta',
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('clima', models.CharField(max_length=200)),
                ('recomendaciones', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('compania', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.grupo')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trail.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('parentesco', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacto_emergencia',
            },
        ),
        migrations.CreateModel(
            name='HorarioRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_retorno', models.TimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='trail.cita')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trail.contactoemergencia')),
            ],
            options={
                'db_table': 'horario_retorno',
            },
        ),
    ]
