# Generated by Django 5.2.6 on 2025-10-28 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trail', '0002_remove_horarioretorno_contacto_and_more'),
        ('users', '0003_usuario_session_activa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tipousuario'),
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('parentesco', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contacto_emergencia',
            },
        ),
        migrations.CreateModel(
            name='HorarioRetorno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_retorno', models.TimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='trail.cita')),
                ('contacto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.contactoemergencia')),
            ],
            options={
                'db_table': 'horario_retorno',
            },
        ),
    ]
