# Generated by Django 5.2.6 on 2025-10-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuario_tipo_usuario_contactoemergencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioretorno',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
